#!/usr/bin/python3

import sys
import requests
from bs4 import BeautifulSoup

url = "https://ja.wikipedia.org/"

def main():
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")
        today = soup.find("div", attrs={"id":"on_this_day"}).text
        print(today)
    except Execption as e:
        print(e)
    finally:
        print('finish')
    return 0

if __name__ == '__main__':
    sys.exit(main())
